version: '3.8'
services:
  crudapp-postgresql:
    image: postgres:13.2
    # volumes:
    #     - ~/volumes/jhipster/crudApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=crudapp
      - POSTGRES_PASSWORD=crudapp123
      - POSTGRES_DB=crudapp
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
